/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-scan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/owner-checks`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/overview` | `/overview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/scans` | `/scans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/scans` | `/scans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/owner-checks`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/overview` | `/overview`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/scans` | `/scans`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(employee)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(employee)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(employee)'}/scans` | `/scans`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(employee)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-scan${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/owner-checks${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/overview${`?${string}` | `#${string}` | ''}` | `/overview${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/scans${`?${string}` | `#${string}` | ''}` | `/scans${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(employee)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(employee)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(employee)'}/scans${`?${string}` | `#${string}` | ''}` | `/scans${`?${string}` | `#${string}` | ''}` | `${'/(employee)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-scan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/owner-checks`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/overview` | `/overview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/scans` | `/scans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/scans` | `/scans`; params?: Router.UnknownInputParams; } | { pathname: `${'/(employee)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; };
    }
  }
}
