import { ArrowRight, Monitor, Printer, Route, SquareStack } from 'lucide-react'

function Flow({ title, help, steps, tone }) {
  return <div className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex items-center gap-2">{tone === 'hardware' ? <Printer className="h-4 w-4 text-dash-gold" /> : <Route className="h-4 w-4 text-emerald-300" />}<h3 className="text-sm font-semibold">{title}</h3></div><p className="mt-1 text-xs leading-5 text-dash-tertiary">{help}</p><div className="mt-3 flex flex-wrap items-center gap-2">{steps.map((step, index) => <div key={step.label} className="contents"><span className="rounded-lg border border-white/10 bg-white/[0.035] px-3 py-2 text-xs"><strong className="block text-dash-cream">{step.label}</strong><span className="text-dash-tertiary">{step.detail}</span></span>{index < steps.length - 1 && <ArrowRight className="h-3.5 w-3.5 text-dash-tertiary" />}</div>)}</div></div>
}

export default function HardwareChainGuide() {
  return <section className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start gap-3"><SquareStack className="mt-0.5 h-5 w-5 text-dash-gold" /><div><p className="label-mono">Connection truth</p><h2 className="mt-1 text-lg font-semibold">Hardware and production are separate chains</h2><p className="mt-1 text-sm text-dash-tertiary">A terminal’s cash drawer path does not decide where food or drinks are produced. Configure and troubleshoot each chain independently.</p></div></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Flow tone="hardware" title="Terminal hardware chain" help="Used for receipts and drawer commands. The backend records issued/acknowledged state; physical opening still depends on the configured transport and pulse." steps={[{ label: 'POS terminal', detail: 'paired device' }, { label: 'Receipt printer', detail: 'network, USB, or system transport' }, { label: 'Drawer port', detail: 'printer-attached port' }, { label: 'Pulse', detail: 'pin, on/off timing' }]} /><Flow tone="production" title="Production routing chain" help="Used for kitchen and bar work. Item/category and service section resolve a production station; the station fans out to named KDS and printer targets." steps={[{ label: 'Service section', detail: 'order/table context' }, { label: 'Production station', detail: 'bar, prep, expo' }, { label: 'Output target', detail: 'named KDS or printer' }, { label: 'Shift access', detail: 'queue visibility only' }]} /></div><div className="mt-3 flex items-center gap-2 text-xs text-dash-tertiary"><Monitor className="h-3.5 w-3.5" /> Terminal-to-station access controls which KDS queues an employee may see; it never replaces item/section routing.</div></section>
}
